### ISSUE TITLE
Missing instructions on installing json-tree?

### ISSUE THREAD

**Issue by saada** [carbon-tools/carbon#25]
So I tried running `git submodule init` and then `grunt serve`. The demo ran fine but I can't see the json-tree generated on the right-hand side at all.
Not sure what I'm doing wrong.
Thanks

**Comment by saada** [comment]
Some console log errors in the browser

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8000/libs/json-tree/jsontree.js Failed to load resource: the server responded with a status of 404 (Not Found)
(index):35 Uncaught ReferenceError: JSONTree is not defined
```

**Comment by mkhatib** [comment]
Thanks @saada good points.

Try running `git submodule update --init --recursive`

Or freshly clone the editor repo with `--recursive` flag like `git clone --recursive git://github.com/manshar/editor.git`

I am adding these to the Development section in the README

**Comment by saada** [comment]
that fixed it. I'm gonna update the README

**Comment by mkhatib** [comment]
Sweet thanks :+1:
