### ISSUE TITLE
Inserting Lists

### ISSUE THREAD

**Issue by mkhatib** [carbon-tools/carbon#6]
Ordered and unordered lists, whether through syntactic analysis and replacement (typing "1." followed by space at the beginning of the line would trigger an ordered list) or through formatting bar.

**Comment by saada** [comment]
I can work on this one. I can add a case statement [here](https://github.com/manshar/editor/blob/master/src/editor.js#L233) for the "space" key and check if the previous character is 
- '.' for ordered lists (i.e. you type '1. ', '2. ')
- '*' for unordered lists such that if you type: '\* ' (asterisk + space)

What do you think? And is this the best place to write this logic?

**Comment by mkhatib** [comment]
I haven't thought of text context triggers of formatting (at some point we want this), for now maybe work with the [Formatting block toolbar](https://github.com/manshar/editor/blob/master/src/extensions/formatting.js#L85) (add a button for UL and one for OL) and handle that in [handleBlockFormatting method](https://github.com/manshar/editor/blob/master/src/extensions/formatting.js#L507).

I think one tricky thing about lists is that they have a parent component `ul` and child components `li`. And there will need to be a way to handle insertParagraph for LIs. Not sure if we should represent the LI as the paragraph or the UL. Need some experimentation or maybe some thinking to be done there.

What do you think?

**Comment by saada** [comment]
I see your train of thought. Random question... Have you thought of using a framework such as React?
The reason why I'm even suggesting this is that React allows you for very powerful component structure and code layout that I think fits the editor use case pretty well. 

In regards to this issue, we could have a UL component which renders within it an array of LI components. Then, LI components can simply render PARAGRAPH component. Which could have itself its own UL components and so on. (recursive components)

And the structure kind of lays itself. But, React or not, that's how I would treat it. A recursive component tree basically.

**Comment by saada** [comment]
Basically the current pipeline seems to be laid out as:

`user action -> DOM manipulation -> JSON model`

React would turn it more into

`user action -> JSON model -> DOM re-render`

**Comment by saada** [comment]
I guess I digressed a little here. Here's another approach with the current system. We could just have a paragraph of type "UL" which just adds a bullet point in front of the paragraph and the following paragraph would default to a UL paragraph. No LIs would be required, they're just regular paragraphs.

The same logic can be applied to OLs. Consecutive OLs will have incremental digits in front of their paragraphs. No LIs required.

**Comment by saada** [comment]
So after experimenting a little bit, i got a basic editor working nicely with React based a json string that looks like this

``` json
{
  "sections":[
    {
      "component": "h1",
      "content": "header 1"
    },
     {
      "component": "h2",
      "content": "header 2"
    },
  ]
}
```

I'll clean up my code a bit and show you my branch sometime tonight.

**Comment by mkhatib** [comment]
Thanks @saada. I really would like to build the editor away from any frameworks. One choice we can use is the new Web Components APIs to do something similar to what you are suggesting.

As for the ULs being rendered as paragraphs, it's a cool idea and would probably make it easier to implement it, my concern would be breaking the default copying of the rendered paragraph as we'll be just copying paragraphs instead of the LIs. I think it's better if we stick to any component there's already a native element for and not try to emulate how they look using other ones.

The current state of the editor is actually:
`user action -> json model change -> update dom` 

For most `user actions`. I believe so far only `cut` action handle this differently:
`cut action -> DOM update AND json model update`

Overall I could really use some help with writing better code for making the editor into smaller components. For example, I was trying to build the Formatting module as a separate extension that users can replace and write different ones if they'd like, but looking at it now it's very coupled. I'd love to go back at some point and refactor some of it to make it as decoupled as possible to allow this kind of extensibility.

Have you made progress on the React experiment, would love to see it.
