### ISSUE TITLE
Strange Input when writing/editing 

### ISSUE THREAD

**Issue by Pandahisham** [carbon-tools/carbon#71]
Sometimes the cursor gets a mind of it's own and jump back or forth , tested on the demo site using ios 9.2 .

Also if i put cursor on word and select a replacement from the virtual keyboard , sometimes the words get jumbled

**Comment by mkhatib** [comment]
We haven't done much testing on iOS to be honest, any feedback and steps to reproduce would be awesome so we can test it out. For example, what were you doing when the cursor jumped? 

Thanks for the report will look into it.

**Comment by Pandahisham** [comment]
tested again , happens all over the demo site

**Comment by mkhatib** [comment]
@Pandahisham thanks for testing this. We moved to a different way of handling input in Carbon, mind giving it another pass and see how this is working now?

For the words replacements from virtual keyboard suggestions I'll file a separate bug I can see this is still buggy most of the time.

**Comment by Pandahisham** [comment]
tested 
1. cursor seems stable 
2. cursor stays in position when selecting replacement words 

all green , but there's a new issue , i am putting as a separate entry  #98

**Comment by mkhatib** [comment]
Cool thanks for testing this. Closing this for now, will follow up on other bug
