### ISSUE TITLE
/giphy <searchterm> not working 

### ISSUE THREAD

**Issue by Pandahisham** [carbon-tools/carbon#73]
tested on ios 9.2

**Comment by mkhatib** [comment]
Hey @Pandahisham, we have changed the syntax to be `+giphy <search term>` instead. Can you try that?

**Comment by Pandahisham** [comment]
yes it is working m
however i noticed a bad user experience -- some people add a trailing space by habit and it breaks the functionality , i think the regex should have a trialing space in it
