### ISSUE TITLE
Auto-merge multiple empty lines at the end of an article

### ISSUE THREAD

**Issue by AhmedGaber** [carbon-tools/carbon#77]
That's what happens when a user append multiple empty lines at the end of the article, check this article: https://www.manshar.com/articles/3582/

We need to automatically merge these trailing empty lines.

**Comment by mkhatib** [comment]
Thanks for filing! This has actually been fixed by #52 but we haven't deployed to Manshar the latest updates of Carbon. Waiting on a change I am making to fix a bug in production.
