### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by Abdulla2** [carbon-tools/carbon#78]
There are many issues many other browsers than chrome.
I had many issues recently while I am using Firefox but this is the worst.
I wrote an article in a simple text editor then I copied it to manshar :
![this picture](http://i.imgur.com/2UeAUMI.png)

هناك عدة مشاكل مع المتصفحات ما عدا كروم. 
منذ فترة بدأت استعمال فيرفوكس وواجهتني عدة مشاكل ولكن كانت هذه هي الأسوأ:
![this picture](http://i.imgur.com/2UeAUMI.png)

**Comment by mkhatib** [comment]
Closing this Filed under appropriate repo.
