### ISSUE TITLE
Backspace issues

### ISSUE THREAD

**Issue by assembledadam** [carbon-tools/carbon#85]
Go to the demo: https://www.carbon.tools/demo/index.html

Select a paragraph midway down the page, and just hold your finger on backspace.

It deletes the paragraph fine, until it gets to the preceding paragraph, upon which it appends the text you just deleted to the end. Could be that the key press events are happening too quickly for the editor?

One other strange behaviour, probably related: holding backspace for just longer than you would normally when deleting deletes the character onpress, and then puts it back onkeyup.

Using Chrome 50 on a Mac.

**Comment by mkhatib** [comment]
Thanks for the filing this @assembledadam 

I got a fix locally for the backspace but still working on getting this to work for the delete key as well the behavior there is even weirder... will try to get the fix soon.

**Comment by mkhatib** [comment]
Found the problem with holding delete have a quick fix but working on seeing if this might also need to be applied in other situations.

**Comment by assembledadam** [comment]
Just merged in the fix and this is working wonderfully! Thanks

As I think I mentioned before, I'm still working extremely hard on a project at the moment ready for launch soon (a number of weeks), once I'm on the other side of that I will try to give you hand with the other bugs + features.
