### ISSUE TITLE
Bugs with accents on Mac and PC

### ISSUE THREAD

**Issue by assembledadam** [carbon-tools/carbon#88]
It seems I'm really taking the editor for a road test with my use cases! Anyway there are some issues I've experienced:

**On a PC**

Generally works well - `ALTGR + e` = é, `ALTGR + o` = ó, works as expected, however `ALTGR + a` selects all text rather than producing the expected á.

**On a Mac**

It seems that accents are generally broken in the editor on a mac. The reason appears to be the way you produce characters on a mac, using any kind of mac keyboard (UK or European).

> FYI: I'm going to refer to the mac 'alt' key as option here, for your reference

To produce accents, there is an 'accents key' - on international keyboards this is a single key, on UK/US keyboards, you press `option + e`.  After pressing the accents key (which shows up as ´, often highlighted) you press the key corresponding to the vowel you want.  For example: á.  

Try this in any standard editor and you see how it works.  Example:

Standard editor: `option + e, a` produces á
Carbon editor: `option + e, a` produces ´a

**Solution**

The PC solution should be fairly trivial - unassigning or being more specific for select all (which on a PC should be `CTRL + a` rather than `ALT + a` or `ALTGR + a`).

For Mac, I think the fix should also be fairly easy - it just involves some extra keyboard detection.  See: http://stackoverflow.com/questions/25332625/detect-accented-chars-typed-on-mac

Again I will give you a hand when I get time. Thanks.

**Comment by mkhatib** [comment]
> It seems I'm really taking the editor for a road test with my use cases! Anyway there are some issues I've experienced:

Thank you so much for filing all of these! These are great and will try my best to address them as fast as I can! 

Thanks for the solution proposals and the links, I don't use accents so this test case would never have came to life if you haven't filed it 👍 thanks for that. Will do some more reading about it and see the link you sent.

**Comment by assembledadam** [comment]
No problem, plenty where that came from ;)

I always feel guilty posting bugs on open source software - in most cases for other projects I don't do this without providing a fix, so I appreciate you being so gracious! Like I said, my aim is to assist as soon as I am able - right now my hours are almost entirely dedicated to finishing the beta of my company's platform (for the noble pursuit of survival...).

**Comment by mkhatib** [comment]
haha. I love working on Carbon (most of the time I only get to work on it on weekends - sometimes after hours) so having someone actively engaged is pretty exciting for me so please keep the bugs coming 😄

**Comment by assembledadam** [comment]
It's an excellent editor, even in its alpha state. It's also well written, although I think could be more extensible (I have had to fork the project to add my own functionality). This is only because I need something fairly stable and live ASAP, obviously the right way of doing this is to restructure the editor to allow additional functionality without editing the core (as discussed in the other issue).

Right now the platform I am building will make use of Carbon for a dozen or so site editors/staff (with daily use).  Once that is stable (with several other features of the site), we will open it up to all users with a wikipedia style approach. Our sites reach a few million users a month so this will be a great test :)

**Comment by mkhatib** [comment]
> although I think could be more extensible

I really would love to spend more time on fixing the extensibility of carbon after closing high priority bugs. There are a lot of work that can be done there to make this excellent! (lazy loading extensions is one of them) - extensions need to be rethought to make this better.

> Our sites reach a few million users a month so this will be a great test :)

Awesome 💃! Pretty excited to see how this go for you! Good luck. And feel free to bug me if a bug needs attention fast I can try my best to get it fixed quickly - a lot of the times these annoying bugs are easily fixed.

I'll try to draft a new design document about extensions in carbon and will invite you to get your input on it.

**Comment by assembledadam** [comment]
We're using this in production now (over at https://www.videogamer.com - only staff are able to edit at the moment), and will be launching an international version of the site this month, so the accents issue will definitely become a bigger problem for us.  Going to try to take a look at it ASAP, but any help would be great on this particular issue :)

If you'd like, at some point I could show you a demo of how we're using it (with a few mods!).

**Comment by mkhatib** [comment]
@assembledadam I [have a change](https://github.com/manshar/carbon/pull/102) that fixes this! It took a bit of work thanks to many funky Javascript stuff, [including `keyCode` inconsistencies between key handlers](https://twitter.com/mkhatib7/status/795145727156436992).

I need some help to test the two issues you are seeing on other platforms, I only tried this on Mac Chrome. 

Would you be able to pull that change locally and test it out (or patch it into your fork to test it out there).

I'll also continue to do some more testing for this but would appreciate other eyes on this as well 👀

**Comment by mkhatib** [comment]
Oh. And would love to see it in action 😄 jump on a video chat? What timezone you're in?

**Comment by ahyield** [comment]
![](https://i.chzbgr.com/full/6041904384/hE824FBB3/)
