### ISSUE TITLE
Enhancement: Allow easy continuous text editing after embed

### ISSUE THREAD

**Issue by assembledadam** [carbon-tools/carbon#95]
If you put an embed at the very end of an article/the editor, there is no an intuitive way to add text after it.

Right now the only way to add a new paragraph/'layout' of text appears to be to select the caption and hit enter.

I think the ideal here would to always ensure there's an empty paragraph of text at the bottom of the editor, or at least putting one there automatically if it's detected it is the last element in the JSON (probably easier).

Then when rendering the output HTML it removes any empty final paragraph(s).

**Comment by mkhatib** [comment]
> Right now the only way to add a new paragraph/'layout' of text appears to be to select the caption and hit enter.

If you hit enter when the embed is selected it should insert a paragraph right after it allowing you to continue adding text. If you're seeing something different please let me know.

I thought about always having an empty paragraph as you suggest but wasn't entirely sure if it's the best thing, I am open to considering it if you find the enter when the embed is selected is a bit unintuitive.

**Comment by assembledadam** [comment]
Aha. I opened a 'fresh' version of the demo and it works there. It must be something to do with the specific components I have put in the demo. Let me have a play and see if I can figure out what it is.

**Comment by mkhatib** [comment]
Btw this was also broken after #86 and before #90 so you might have been hitting that.

**Comment by mkhatib** [comment]
Closing this issue as it should be fixed. Please reopen if still having a problem.
